### PR TITLE
Added journal

### PR DESCRIPTION
**Pull request by tswise**

### CODE REVIEW

**Comment by colagrosso** [comment]
Looks good. That project has a lot of open pull requests. I hope yours gets merged. If you want to commit this file to the `in-progress` directory as-is, that's fine. The `completed` directory is for changes that have already been merged.

**Comment by colagrosso** [comment]
Ping.

**Comment by colagrosso** [comment]
Ping.

**Comment by tswise** [comment]
recommitting file now

**Comment by colagrosso** [comment]
Looks like your pull request on the lawyersongithub didn't get addressed. That's too bad, but it happens.

For this project: If you want to commit this file to the `in-progress` directory as-is, that's fine. The `completed` directory is for changes that have already been merged.

**Comment by colagrosso** [comment]
Closing this one in favor of https://github.com/colagrosso/csci-4830-821-hw2-journal/pull/10.

**Comment by tswise** [comment]
I'm afraid I don't follow. Did I added the new file correctly?

**Comment by colagrosso** [comment]
Yes, you're set. You accidentally made another pull request: https://github.com/colagrosso/csci-4830-821-hw2-journal/pull/10. I merged that one and closed this one.

**Pull request closed without merging**
